# Generated by Django 3.2 on 2023-07-10 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_alter_funcionario_user'),
        ('documentos', '0002_documento_documento_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='documento_funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario'),
            preserve_default=False,
        ),
    ]
